// GENERATED by scripts/check-posts.mjs from each post's `export const meta`.
// Do not edit: change the .mdx and run `node scripts/check-posts.mjs`.
import type { BlogPost } from "./types";

export const posts = [
  // audio-thread.mdx
  {
    slug: "audio-thread",
    title: "Building a sampler with 2.7 milliseconds to spare",
    date: "2026-09-22",
    author: "Daniel Oh",
    summary:
      "Sixteen pads inside my Windows 98 desktop. Rust made the engine 2.3 times faster, but keeping the audio running took more than that.",
    tags: ["engineering", "audio", "launch"],
    readingTime: "6 min",
    image: "/blog/sampler/sampler.jpg",
    imageWidth: 1600,
    imageHeight: 1244,
    imageAlt:
      "The Sampler program open on the danoh.com desktop: a four by four grid of pads labelled with keyboard keys and drum names, a waveform of the kick, a volume slider and level meter, 12-bit and Vinyl switches, and a sixteen step row with the playhead running.",
    imageCaption:
      "Sixteen pads, a step sequencer, and a 12-bit switch for roughing things up.",
  },
  // camera.mdx
  {
    slug: "camera",
    title: "I put a 1998 webcam on my website",
    date: "2026-09-21",
    author: "Daniel Oh",
    summary:
      "A camera window for my desktop-style website. Sixteen colours, chunky pixels, and a photo you can save to My Pictures.",
    tags: ["launch", "portfolio", "design"],
    readingTime: "2 min",
  },
  // background-remover.mdx
  {
    slug: "background-remover",
    title: "4 GB to 76 MB: open-sourcing Kayrage's background remover",
    date: "2026-09-17",
    author: "Daniel Oh",
    summary:
      "Kayrage's Darkroom removes a background in one tap. I rewrote its 4 GB Python service as a 76 MB Rust binary and open-sourced it.",
    tags: ["engineering", "infrastructure", "launch"],
    readingTime: "6 min",
    image: "/blog/background-remover/before-after.jpg",
    imageWidth: 1600,
    imageHeight: 912,
    imageAlt:
      "The Kayrage Darkroom editor. Left: a portrait with its background, the cursor on the Cutout chip. Right: the same portrait on transparency, with a toast reading 'Background removed.'",
    imageCaption:
      "One chip in the Darkroom. Left, the photo as cropped. Right, about two seconds later.",
  },
  // three-pivots-and-a-lowercase-k.mdx
  {
    slug: "three-pivots-and-a-lowercase-k",
    title: "Three pivots and a lowercase k",
    date: "2026-08-27",
    author: "Daniel Oh",
    summary:
      "August across the sites: three changed what they are, one got rebuilt in six waves, and a typeface's k went through seven angles. What it actually cost.",
    tags: ["portfolio", "engineering", "ai"],
    readingTime: "8 min",
  },
  // one-day-128-feelings.mdx
  {
    slug: "one-day-128-feelings",
    title: "One day, 128 feelings: shipping findmyfeels.com",
    date: "2026-08-03",
    author: "Daniel Oh",
    summary:
      "I built findmyfeels.com in a day: a private check-in, a 128-word emotion wheel, and an AI room with hard safety rails. Notes on where the day went.",
    tags: ["launch", "ai", "engineering"],
    readingTime: "5 min",
  },
  // eleven-sites-one-operator.mdx
  {
    slug: "eleven-sites-one-operator",
    title: "Eleven sites, one operator",
    date: "2026-07-21",
    author: "Daniel Oh",
    summary:
      "A tour of the work: eleven live sites shipped mostly in the last few months, and the reason one person can run that many. Screenshots, not adjectives.",
    tags: ["portfolio", "engineering", "ai"],
    readingTime: "7 min",
  },
  // letting-fable-5-loose.mdx
  {
    slug: "letting-fable-5-loose",
    title: "Letting Fable 5 loose on this site",
    date: "2026-06-10",
    author: "Daniel Oh",
    summary:
      "The desktop got a boot sequence, 3D Pipes, and genie windows in one long run with Claude's Fable 5 model. Field notes from the passenger seat.",
    tags: ["ai", "engineering"],
    readingTime: "4 min",
  },
  // two-sites-one-operator.mdx
  {
    slug: "two-sites-one-operator",
    title: "Two sites, one operator",
    date: "2026-05-11",
    author: "Daniel Oh",
    summary:
      "A second site this month, for consulting work this one was never going to do. Notes on why one channel cannot carry both jobs.",
    tags: ["brand", "writing", "consulting", "ai"],
    readingTime: "3 min",
  },
  // building-floeberg.mdx
  {
    slug: "building-floeberg",
    title: "Self-hosting Supabase Auth (gotrue): the Floeberg build log",
    date: "2026-05-11",
    author: "Daniel Oh",
    summary:
      "Build log for floeberg.com. Why I self-hosted gotrue, how Stripe → DB → Discord stays idempotent, and one chat table projected to two surfaces.",
    tags: ["engineering", "infrastructure", "ai", "consulting"],
    readingTime: "4 min",
  },
  // mdx-rive-demo.mdx
  {
    slug: "mdx-rive-demo",
    title: "Rive in MDX: live React components in a Next.js blog",
    date: "2026-04-17",
    author: "Daniel Oh",
    summary:
      "The blog migrated to MDX so posts can include real React. Here is a 4 KB Rive animation rendered inline as proof.",
    tags: ["engineering", "mdx", "rive"],
    readingTime: "2 min",
  },
  // welcome-to-danoh.mdx
  {
    slug: "welcome-to-danoh",
    title: "Welcome to danoh.com",
    date: "2026-04-09",
    author: "Daniel Oh",
    summary:
      "A retro Windows 98 desktop where any program you describe gets generated by Claude in seconds. Here is what is running underneath.",
    tags: ["launch"],
    readingTime: "2 min",
    pinned: true,
  },
  // ai-app-generation.mdx
  {
    slug: "ai-app-generation",
    title: "How AI app generation works",
    date: "2026-04-10",
    author: "Daniel Oh",
    summary:
      "Behind the Run program: how a sentence becomes a working HTML/CSS/JS app in seconds, and where the AI takes shortcuts you would never notice.",
    tags: ["engineering", "ai"],
    readingTime: "3 min",
  },
] satisfies BlogPost[];
